### ISSUE TITLE
How to add the speedometer into a surfaceview

### ISSUE THREAD

**Issue by aopaw** [bilthon/Android-Speedometer#6]
Hi, Bilthon.

Thank you very much for this project. I try using you speedometer for my project. Here is a snapshot of my project view. The background color and the icon (refresh button like icon) are given onto a surfaceview. The button is actually a bitmap by far and doing nothing. I am trying to monitor 
 the button press via coordinate measuring in onTouchEvent. So in this case, there was a draw() to show all these. 
I just put your speedometer.java and its listener into my project. Of course, the attr.xml is included. 
I declare a private object of speedo in my surfaceview and give the findviewById() into the draw(). However, it is not visible as shown by the snapshot. I cannot find out why at this moment. This is the second week since I know android development. A little bit difficulties to handle the problem. 
![Screenshot_2019-11-07-14-23-04](https://user-images.githubusercontent.com/54405468/68370809-4abfab80-0178-11ea-96a4-4b00d6536d02.jpeg)

**Comment by bilthon** [comment]
Hi there, I'm not sure I understand your setup. Maybe if you share some code it would make it easier.

**Comment by aopaw** [comment]
Hi, @bilthon. It works now.
